// This file is generated by Slice Machine. Update it when you push changes.
// For now, we define placeholder types until Slice Machine generates real ones.

import type * as prismic from "@prismicio/client";

declare module "@prismicio/client" {
  interface Content {
    HomepageDocument: prismic.PrismicDocumentWithUID;
    ServicePageDocument: prismic.PrismicDocumentWithUID;
    BlogPostDocument: prismic.PrismicDocumentWithUID;
    NavigationDocument: prismic.PrismicDocument;
    HeroSlice: prismic.SharedSlice;
    FeatureCardsSlice: prismic.SharedSlice;
    StepperSlice: prismic.SharedSlice;
    PlanningSlice: prismic.SharedSlice;
    GlobeSectionSlice: prismic.SharedSlice;
    LogoCloudSlice: prismic.SharedSlice;
    BlogSectionSlice: prismic.SharedSlice;
    TimelineSlice: prismic.SharedSlice;
    BannerSectionSlice: prismic.SharedSlice;
    RichTextSectionSlice: prismic.SharedSlice;
    FormSectionSlice: prismic.SharedSlice;
  }
}
